version: '3.9'
services:
  mongo:
    container_name: mongo
    image: mongo:5.0.22
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    container_name: redis
    image: redis:7.2.3-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  mongo-data:
    driver: local
