version: '3.9'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./build/server/Dockerfile
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/
      AUTH_REDIS_URL: auth-redis:6379
      DID_REDIS_URL: did-redis:6379
    depends_on:
      - mongo
      - auth-redis
      - did-redis

  swagger:
    container_name: swagger
    build:
      context: .
      dockerfile: ./build/swagger/Dockerfile
    restart: always
    ports:
      - 1323:1323

  mongo:
    container_name: mongo
    image: mongo:5.0.22
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  auth-redis:
    container_name: auth-redis
    image: redis:7.2.3-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf

  did-redis:
    container_name: did-redis
    image: redis:7.2.3-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  mongo-data:
    driver: local
